export const EnterAnimations = {
    fadeIn: "fadeIn",
    fadeInUp: "fadeInUp",
    fadeInDown: "fadeInDown",
    fadeInDownBig: "fadeInDownBig",
    fadeInUpBig: "fadeInUpBig",
    fadeInLeft: "fadeInLeft",
    fadeInLeftBig: "fadeInLeftBig",
    fadeInRight: "fadeInRight",
    fadeInRightBig: "fadeInRightBig",
    flipInX: "flipInX",
    flipInY: "flipInY",
    slideInDown: "slideInDown",
    slideInUp: "slideInUp",
    slideInLeft: "slideInLeft",
    slideInRight: "slideInRight",
    zoomIn: "zoomIn",
    zoomInDown: "zoomInDown",
    zoomInUp: "zoomInUp",
    zoomInLeft: "zoomInLeft",
    zoomInRight: "zoomInRight",
};